#!/bin/sh
set -eu
IFS="$(printf '%b_' '\n\t ')"
IFS="${IFS%_}"

brew install cabal-install &&
    brew uninstall --ignore-dependencies ghc &&
    brew install ghc@8.2 &&
    brew link --force --overwrite ghc@8.2 &&
    echo 'export PATH="$PATH:/Users/vagrant/.cabal/bin"' >>/Users/vagrant/.bash_profile
